### ISSUE TITLE
How to stop the alarm once it goes off?

### ISSUE THREAD

**Issue by marc2377** [shaggytwodope/alarm-clock#2]
Using Arch Linux with Cinnamon.

I had configured an alarm clock for a few minutes ago. I closed it (to tray).

At the scheduled time, the alarm sound started ringing. But, I couldn't figure out how to stop it. Eventually I just quit the application.

How do I stop an on-going alarm?

**Comment by shaggytwodope** [comment]
Currently the way to stop an alarm is to hit the stop button (the square button) in the main window.

**Comment by marc2377** [comment]
Ah. Thanks.

**Comment by shaggytwodope** [comment]
Feel free to close the issue if it works for you as mentioned.
